name: iris
description: "IRIS - Blind Assist Obstacle Detection App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  tflite_flutter: ^0.11.0
  flutter_tts: ^4.2.0
  vibration: ^2.0.0
  image: ^4.3.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/yolov8n.tflite
    - assets/midas_v21_small_256.tflite
